name: CI Automatizacion

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover tests

      - name: Generate coverage report
        run: |
          pip install coverage
          coverage run -m unittest discover tests
          coverage report -m

      - name: Check coverage
        run: |
          coverage xml
          pip install coverage-threshold
          coverage-threshold --coverage-file coverage.xml --threshold 80

      - name: Run flake8
        run: |
          pip install flake8
          flake8 .