name: CI Ingenieria de Software

on:
  push:
    branches:
      - '**' # Incluye todas las branch
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"] # Versiones de desarrollo de Software

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencias
        run: |
          py -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittesting
        run: |
          py -m unittest discover tests

      - name: Generate reporte de cobertura
        run: |
          pip install coverage
          coverage run -m unittest discover tests
          coverage report -m

      - name: Check cobertura
        run: |
          coverage xml
          pip install coverage-threshold
          coverage-threshold --coverage-file coverage.xml --threshold 80

      - name: Run flake8
        run: |
          pip install flake8
          flake8 .